services:
  node:
    build: 
      context: ./node
      dockerfile: Dockerfile
    container_name: server-container
    ports:
       # Host port:Container port
      - '4000:4000'
    volumes:
      - ./node:/app
      - /app/node_modules
    networks:
      - my_network

  react:
    build: 
      context: ./client
      dockerfile: Dockerfile
    container_name: client-container
    ports:
     # Host port:Container port
      - '3000:3000'
    # volumes:
    #   - ./client:/app
    stdin_open: true
    networks:
      - my_network
      
networks:
  my_network:
    driver: bridge